language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install Cython
  - pip install msgpack-python
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest-flake8
  - pip install coveralls
  - python setup.py install
script:
  - python setup.py build_ext --inplace
  - pytest --verbose --doctest-modules --flake8 --cov=maxentpy
after_success:
    - coveralls
